{"ast":null,"code":"import { display } from './display';\nexport function catchUserErrors(fn, errorMsg) {\n  return function () {\n    var args = [];\n\n    for (var _i = 0; _i < arguments.length; _i++) {\n      args[_i] = arguments[_i];\n    }\n\n    try {\n      return fn.apply(void 0, args);\n    } catch (err) {\n      display.error(errorMsg, err);\n    }\n  };\n}","map":{"version":3,"mappings":"AAAA,SAASA,OAAT,QAAwB,WAAxB;AAEA,OAAM,SAAUC,eAAV,CAAiDC,EAAjD,EAA2EC,QAA3E,EAA2F;EAC/F,OAAO;IAAC;;SAAA,yCAAa;MAAbC;;;IACN,IAAI;MACF,OAAOF,EAAE,MAAF,CAAE,MAAF,EAAME,IAAN,CAAP;IACD,CAFD,CAEE,OAAOC,GAAP,EAAY;MACZL,OAAO,CAACM,KAAR,CAAcH,QAAd,EAAwBE,GAAxB;IACD;EACF,CAND;AAOD","names":["display","catchUserErrors","fn","errorMsg","args","err","error"],"sourceRoot":"","sources":["../../src/tools/catchUserErrors.ts"],"sourcesContent":[null]},"metadata":{},"sourceType":"module"}